"""Added lists table and list_id column

Revision ID: 4af7ea481a53
Revises: 2721ad511178
Create Date: 2025-03-19 22:57:52.684703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4af7ea481a53'
down_revision: Union[str, None] = '2721ad511178'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_lists_id'), 'lists', ['id'], unique=False)
    op.add_column('books', sa.Column('list_id', sa.Integer(), nullable=False))
    op.drop_constraint('unique_book', 'books', type_='unique')
    op.create_foreign_key(None, 'books', 'lists', ['list_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.create_unique_constraint('unique_book', 'books', ['title', 'author'])
    op.drop_column('books', 'list_id')
    op.drop_index(op.f('ix_lists_id'), table_name='lists')
    op.drop_table('lists')
    # ### end Alembic commands ###
