"""add genres column to books

Revision ID: bec748e499dc
Revises: 318fda270af1
Create Date: 2025-02-09 21:57:40.024243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bec748e499dc'
down_revision: Union[str, None] = '318fda270af1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('genre', sa.String(), nullable=True))
    op.create_index(op.f('ix_books_genre'), 'books', ['genre'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_books_genre'), table_name='books')
    op.drop_column('books', 'genre')
    # ### end Alembic commands ###
