"""Added cover_url column

Revision ID: ef454a1d4ba5
Revises: 4af7ea481a53
Create Date: 2025-03-21 13:19:34.948739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef454a1d4ba5'
down_revision: Union[str, None] = '4af7ea481a53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('cover_url', sa.String(), nullable=True))
    op.alter_column('books', 'list_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'list_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('books', 'cover_url')
    # ### end Alembic commands ###
